<?php
namespace Tests\Feature;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;
use App\Models\User;
use App\Models\Project;
use App\Models\BoardColumn;
class AiTest extends TestCase
{
    use RefreshDatabase;
    public function test_ai_handles_column_request()
    {
        $user = User::factory()->create();
        $project = Project::create(['name' => 'Project AI', 'owner_id' => $user->id]);
        $column = BoardColumn::create(['project_id' => $project->id, 'name' => 'AI Column', 'position' => 0]);
        // Intercept Http requests to Gemini API
        Http::fake([
            'generativelanguage.googleapis.com/*' => Http::response([
                'candidates' => [
                    [
                        'content' => [
                            'parts' => [
                                ['text' => json_encode([
                                    'action' => 'create',
                                    'tasks' => [
                                        ['title' => 'Task generated by AI', 'description' => 'Test', 'priority' => 'normal']
                                    ]
                                ])]
                            ]
                        ]
                    ]
                ]
            ], 200),
        ]);
        $response = $this->actingAs($user)->postJson('/api/ai/handle', [
            'column_id' => $column->id,
            'prompt' => 'Generate a task'
        ]);
        $response->assertStatus(200);
        $this->assertDatabaseHas('cards', [
            'title' => 'Task generated by AI',
            'board_column_id' => $column->id
        ]);
    }
    public function test_ai_handles_global_request()
    {
        $user = User::factory()->create();
        $project = Project::create(['name' => 'Global Project', 'owner_id' => $user->id]);
        // Mock Gemini response
        Http::fake([
            'generativelanguage.googleapis.com/*' => Http::response([
                'candidates' => [
                    [
                        'content' => [
                            'parts' => [
                                ['text' => json_encode([
                                    'operations' => [
                                        ['op' => 'create_column', 'name' => 'To Do'],
                                        ['op' => 'create_column', 'name' => 'Done']
                                    ]
                                ])]
                            ]
                        ]
                    ]
                ]
            ], 200),
        ]);
        $response = $this->actingAs($user)->postJson('/api/ai/global', [
            'project_id' => $project->id,
            'prompt' => 'Suggest columns'
        ]);
        $response->assertStatus(200);
        // Check columns were created
        $this->assertDatabaseHas('board_columns', ['name' => 'To Do', 'project_id' => $project->id]);
        $this->assertDatabaseHas('board_columns', ['name' => 'Done', 'project_id' => $project->id]);
    }
}
